### ISSUE TITLE
Conversiones de sistemas numéricos

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-edwin#1]
[Conversiones entre sistemas numericos.pdf](https://github.com/user-attachments/files/16843818/Conversiones.entre.sistemas.numericos.pdf)

**Comment by QUET012** [comment]
portada: 24
Procedimiento:25
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 23
Calificación de la practica: 19.4

**Comment by josealfredo79** [comment]
bien hecho y revisado...
