### ISSUE TITLE
Practica 2 Operaciones con Conjuntos

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-edwin#2]
[Practica 2 Operaciones con Conjuntos.pdf](https://github.com/user-attachments/files/17153413/Practica.2.Operaciones.con.Conjuntos.pdf)

**Comment by josealfredo79** [comment]
Calificacion..???

**Comment by BautistaLizbeth** [comment]
Portada. 5/5
Procedimiento. 5/5
Figuras, ilustraciones y fotografías. 5/5
Resultados y conclusiones. 5/5
Calificación: 20/20

Calificado por: María Lizbeth Bautista García.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
